Fresh token storage
StarProxima/dev_kit pull request #17
Opened 2024-08-28 11:26 UTC by crefter

2024-08-28 12:15 UTC, StarProxima commented on unpublished/project_kit/lib/project_kit.dart
> +export 'package:riverpod_async_builder/riverpod_async_builder.dart';
А зачем? Его, по хорошему, лучше в зависимостях проекта указывать

2024-08-28 17:58 UTC, crefter commented on unpublished/project_kit/lib/project_kit.dart
> +export 'package:riverpod_async_builder/riverpod_async_builder.dart';
Да, но у меня почему-то в слиптери не могли подтянуться зависимости. Типа проект зависит от package:riverpod_async_builder/riverpod_async_builder.dart, пакет зависит от него, и был конфликт (если завтра будет также, покажу скрин). Пока так сделал, чтобы вообще потестить, что и как. Завтра буду смотреть

2024-08-28 21:20 UTC, StarProxima commented on unpublished/project_kit/lib/project_kit.dart
> +export 'package:riverpod_async_builder/riverpod_async_builder.dart';
Это мб из-за того, что надо зависимость с паба поставить, а не с гита

2024-08-29 04:24 UTC, crefter commented on unpublished/project_kit/lib/project_kit.dart
> +export 'package:riverpod_async_builder/riverpod_async_builder.dart';
Аааа, ну да, реально, а я не знал, что ты в паб.дев выложил пакет) Тогда понятно

2024-08-29 09:07 UTC, StarProxima commented on unpublished/project_kit/lib/project_kit.dart
> +export 'package:riverpod_async_builder/riverpod_async_builder.dart';
Да, думаю, что так будет даже чуть проще версионировать для разных проектов, ну мб потом что-то сделаем с этим

2024-08-29 20:38 UTC, StarProxima requested changes

2024-08-29 20:38 UTC, StarProxima commented on unpublished/project_kit/lib/src/utils/token_storage/model/auth_token.dart
> +}
Мы можем добавить сюда nullable userId и проверять его изменение в UserChanged?

2024-08-29 20:38 UTC, StarProxima commented on unpublished/project_kit/lib/src/utils/token_storage/security_token_storage.dart
> +  }
Мб уберём try catch, чтобы можно было выбросить ошибку и она попала в крашлитику?

Только это нужно будет в приложении обработать, чтобы оно не упало при запуске, а просто деавторизавало.

2024-08-29 20:38 UTC, StarProxima commented on unpublished/project_kit/lib/src/utils/token_storage/dio_interceptor/auth_token_interceptor.dart
> +  AuthTokenInterceptor._({
Не уверен, что это корректно называть Interceptor, когда он ещё и функции хранилища выполняет.

Мб что-то типа AuthTokenHandler?

2024-08-29 20:38 UTC, StarProxima commented on unpublished/project_kit/lib/src/utils/token_storage/dio_interceptor/auth_token_interceptor.dart
> +  AuthTokenInterceptor._({
Нужно будет переименовать ещё в приле везде, где он юзается

2024-08-29 20:38 UTC, StarProxima commented on unpublished/project_kit/lib/src/utils/token_storage/security_token_storage.dart
> +  static const _storage = FlutterSecureStorage();
Кстати, видел в ишью, что если создать

```dart
  static const _storage = FlutterSecureStorage(
    aOptions: AndroidOptions(
      encryptedSharedPreferences: true,
    ),
  );
  ```
  
  То он работает лучше и не крашится. Только мб прошлые токены не подтянуться, мб нужно будет писать миграцию, используя два стореджа.

2024-08-29 20:38 UTC, StarProxima commented on unpublished/project_kit/lib/src/utils/token_storage/security_token_storage.dart
> +  }
Мы же тут должны возращать AuthToken?

```suggestion
  Future<AuthToken?> build() async {
    final token =  await read();
    return token;
  }
```

2024-08-30 03:10 UTC, crefter commented on unpublished/project_kit/lib/src/utils/token_storage/model/auth_token.dart
> +}
Хм, возможно, попробую

2024-08-30 03:12 UTC, crefter commented on unpublished/project_kit/lib/src/utils/token_storage/dio_interceptor/auth_token_interceptor.dart
> +  AuthTokenInterceptor._({
Да, думал, как назвать, он по идее хранилище + интерсептор, назвал по простому, чтобы было понятно, что его можно юзать как интерсептор. Хорошо переименую, мб еще подумаю над названием

2024-08-30 03:13 UTC, crefter commented on unpublished/project_kit/lib/src/utils/token_storage/security_token_storage.dart
> +  static const _storage = FlutterSecureStorage();
Хм, хз, возможно. Попробую

2024-08-30 03:13 UTC, crefter commented on unpublished/project_kit/lib/src/utils/token_storage/security_token_storage.dart
> +  }
Конечно, е-мое, не заметил

2024-08-30 05:12 UTC, crefter commented on unpublished/project_kit/lib/src/utils/token_storage/security_token_storage.dart
> +  }
Думаю, можно сделать rethrow, да и достаточно

2024-08-30 05:25 UTC, crefter commented on unpublished/project_kit/lib/src/utils/token_storage/model/auth_token.dart
> +}
Тут проблема - при логине мы получаем только токен, без userId. Хз, как тут быть тогда. При рефреше тоже, получаем только сам токен, без userId. Думаю, лучше оставить только проверку токена, мб.

2024-08-30 06:32 UTC, crefter commented on unpublished/project_kit/lib/src/utils/token_storage/model/auth_token.dart
> +}
Вроде добавил, посмотришь потом в слиптери?

2024-09-03 11:08 UTC, StarProxima approved these changes

2024-09-03 11:08 UTC, merged