Refactor sources for fetchers
StarProxima/dev_kit pull request #43
Opened 2024-11-17 20:20 UTC by iamgirya

2024-11-17 21:35 UTC, StarProxima requested changes

2024-11-17 21:35 UTC, StarProxima commented on app_update/lib/src/sources/release_source.dart
> +  const ReleaseSource.googlePlay({
Зачем нам в ReleaseSource кучу конструкторов, если он нужны только для Source (чтобы было удобно создавать сурсы в коде)?

Если ReleaseSource нужен лишь для того, чтобы скрыть часть инфы, то предлагаю сделать как флаттер команда с BuildContext - пусть ReleaseSource будет интерфейсом, который имплементирует Source, тогда везде в коде можем использоваь Source, а в Release отдавать интерфейс.

2024-11-17 21:35 UTC, StarProxima commented on app_update/lib/src/sources/release_source.dart
> +        _name = null;
Мб лучше везде для конструкторов заменить на

```dart
 const ReleaseSource.appStore({
    required this.url,
    this.platforms = const [UpdatePlatform.ios, UpdatePlatform.macos],
    this.customData,
  })  : type = Sources.appStore,
        _name = null;
```

2024-11-17 21:35 UTC, StarProxima commented on app_update/lib/src/controller/update_controller.dart
> -    Source? defaultSource,
Нам бы всё-таки поддержать логику с target и default сурсами. 
target заменяет любой найденный сурс
default заменяет только если мы не нашли (или нашли, но его нет в глобальных сурсах?)

2024-11-17 21:35 UTC, StarProxima commented on app_update/lib/src/controller/update_controller.dart
> +    String? targetSourceName,
Мне всё также кажется, что использоваться нетипизированных значений для обозначения сурсов - плохая идея.. Когда у нас есть модель Source, которая и нужна, чтобы уйти от стрингов.

Тут, в целом, такая же причина, почему существует UpdatePlatform вместо string и тот же Duration вместо int

2024-11-17 21:35 UTC, StarProxima commented on app_update/lib/src/controller/update_controller.dart
> +    ];
К вопросу о том, что мы должны оставить в списке только уникальные сторы. 

1) Использовать Set, переопределив hashcode и == на сравнение name?
2) Использовать список, но фильтровать после по name?

2024-11-17 21:35 UTC, StarProxima commented on app_update/lib/src/controller/update_controller.dart
> +  Future<List<AppUpdate>> _findAppUpdatesFromConfig({
Мы вроде везде термин Update используем, мб App лишнее

```suggestion
  Future<List<AppUpdate>> _findUpdatesFromConfig({

```

2024-11-17 21:35 UTC, StarProxima commented on app_update/lib/src/controller/update_controller.dart
> +    required bool isFindUpdateFromOneSource,
Вот тут мб уже не очень понятно, мб нужен ренейминг или коммент с докой

2024-11-18 17:50 UTC, iamgirya commented on app_update/lib/src/sources/release_source.dart
> +        _name = null;
Нет, тогда не получится передавать нуллэйбл список в качестве переменной. Сам думал об этом, столкнулся с неприятностью и решить остановиться на вот этом

2024-11-18 17:51 UTC, iamgirya commented on app_update/lib/src/controller/update_controller.dart
> -    Source? defaultSource,
target остался, просто теперь мы чисто targetName передаём (ибо только его и юзали).
Про default сурс и не знал, что у нас такая механика есть. Окей, добавлю

2024-11-18 17:53 UTC, iamgirya commented on app_update/lib/src/controller/update_controller.dart
> +    String? targetSourceName,
Там в коде есть тудушка об этом. Как раз над использованием таргетСурсНэйм. Так что обдажны дойдём до этого

2024-11-18 17:55 UTC, iamgirya commented on app_update/lib/src/controller/update_controller.dart
> +    ];
Да, раньше была такая фича в линкере, но сейчас вижу, что её вырезали. Верну
И да, использовался 1-й способ

2024-11-18 18:29 UTC, StarProxima commented on app_update/lib/src/sources/release_source.dart
> +        _name = null;
Окей, тогда тут можно использовать `platforms` вместо `customPlatforms`? Конфликтов, вроде бы, можно избежать с помощью this

2024-11-18 18:40 UTC, iamgirya commented on app_update/lib/src/sources/release_source.dart
> +        _name = null;
Как же они его тригерят)
Ладно, если не будет проблем, исправлю

2024-11-20 22:31 UTC, iamgirya commented on app_update/lib/src/sources/release_source.dart
> +  const ReleaseSource.googlePlay({
Добавил тудушку, потому что чёт много работы. Давай уже вольём этот пр и потом доделаю. На фичи она не влияет

2024-11-21 10:16 UTC, merged