E2e tests
StarProxima/dev_kit pull request #47
Opened 2024-12-09 15:55 UTC by iamgirya

Единственное, что я не проверял - андроид фетчер. Заюзай впн и прогони пж

2024-12-14 19:59 UTC, StarProxima requested changes

2024-12-14 19:59 UTC, StarProxima commented on app_update/lib/src/fetcher/update_config_fetcher.dart
> +  }
Предполагалось, что byUrl должен идти через hhtp клиент по урлу и получать конфиг, а не по файлу.

Если нам нужен .byFile, то мб предавать туда path, а файл внутри? (но тут хз)

2024-12-14 19:59 UTC, StarProxima commented on app_update/lib/src/finder/update_finder.dart
>      if (sourceCheckerType != null) {
Может внутри тогда обработать?

2024-12-14 19:59 UTC, StarProxima commented on app_update/lib/src/parser/sub_parsers/version_settings_parser.dart
> -    if (unsupportedVersionsValue is! List<String>?) {
Это не так отрабатывало где-то?

2024-12-14 19:59 UTC, StarProxima commented on app_update/lib/src/sources/fetchers/app_store_fetcher.dart
> +    }
Мы точно хотим вот так обрабатывать ошибки?

Мб так будет непонятно, когда не смогли проверить, а когда проверили, а релиза нет

2024-12-14 19:59 UTC, StarProxima commented on app_update/test/e2e/sources_by_platform/sources_by_platform_test.dart
> +        '${Directory.current.path}\\test\\e2e\\sources_by_platform\\sources_by_platform_config.yaml',
Мб такое использование путей не работает на разных системах.

У меня на маке чёт все падает.

Вроде можно использовать пакет path как тестовую зависимость, он должен правильно пути делать.
Тут, кстати, относительные пути не сработают?

![image](https://github.com/user-attachments/assets/2977957a-7ed3-4db3-b007-d7f768f14af7)

<img width="1149" alt="Снимок экрана 2024-12-14 в 22 47 44" src="https://github.com/user-attachments/assets/93f906e9-83b1-44f6-8a83-966aeebd83a6" />

2024-12-14 19:59 UTC, StarProxima commented on app_update/test/e2e/fetcher_by_sources/fetcher_by_sources_test.dart
> +        );
У меня через испанский vpn релиз находит, но releaseNotes нет

И урл другой - "https://play.google.com/store/apps/details?id=com.nullexp.cube_system&hl=en"

Мб его стоит проверять раньше, плюс указать локаль в findUpdate?

2024-12-18 20:12 UTC, iamgirya commented on app_update/lib/src/fetcher/update_config_fetcher.dart
> +  }
Если будем передавать путь, то придётся делать обработку создания файла и прочее внутри. Здесь же мы просто читаем файл, который получаем из вне.

2024-12-18 20:16 UTC, iamgirya commented on app_update/lib/src/finder/update_finder.dart
>      if (sourceCheckerType != null) {
Вылетает ошибка из пакета, что мы юзаем, а именно из `await checker.StoreChecker.getSource. Единственное как можно обработать эту ошибку внутри функции - вернуть null, обернув всю функцию в try catch.
Ну и подумал о том, что легче тогда обрабатывать это во вне

2024-12-18 20:17 UTC, iamgirya commented on app_update/lib/src/parser/sub_parsers/version_settings_parser.dart
> -    if (unsupportedVersionsValue is! List<String>?) {
Да, это ломалось при попытке парсинга в тесте `Sources by platform`. Да и кроме того, это единственное место, где было использован List<String>?, а не List?, так что подумал, что ты просто мог пропустить

2024-12-18 20:23 UTC, iamgirya commented on app_update/lib/src/sources/fetchers/app_store_fetcher.dart
> +    }
Окей, согласен, что это не очень. Тогда просто в контроллере обернул метод в `.onError((_, __) => null)`. Ошибку всё равно придётся обрабатывать, так как иначе она вылетит при вызове контроллера, что не должно быть.

Мб в будущем для таких ситуаций нужно будет добавить логирование

2024-12-18 20:23 UTC, iamgirya commented on app_update/test/e2e/sources_by_platform/sources_by_platform_test.dart
> +        '${Directory.current.path}\\test\\e2e\\sources_by_platform\\sources_by_platform_config.yaml',
Тесты надо запускать из папки app_update
Слеши поправил с помощью пакета, специально для макаюзеров

2024-12-18 20:26 UTC, iamgirya commented on app_update/test/e2e/fetcher_by_sources/fetcher_by_sources_test.dart
> +        );
Урл поправил, а вот с releaseNotes беда. Надо будет подебажить метод их получения. Оставил пока TODO-шку об этом, чуть позже займусь

2024-12-18 20:35 UTC, StarProxima commented on app_update/lib/src/fetcher/update_config_fetcher.dart
> +  }
> то придётся делать обработку создания файла и прочее внутри.

Ну в этом и смысл, чтобы не делать это при использовании .byFile, но ок

2024-12-18 20:36 UTC, StarProxima commented on app_update/lib/src/finder/update_finder.dart
>      if (sourceCheckerType != null) {
Если это проблема пакета, то мб лучше внутри checkAppSource обработать, вряд ли хорошо при использовании учитывать, что там что-то может экзепшен выкинуть

Но тут да, нужно потом логирование добавить, мб тудушку завести

2024-12-18 20:38 UTC, StarProxima commented on app_update/lib/src/parser/sub_parsers/version_settings_parser.dart
> -    if (unsupportedVersionsValue is! List<String>?) {
Вроде это сломается, если список придёт пустым, что, по идее, валидный кейс

Надо будет в других местах тоже посмотреть чекнуть

> List?, а не List?

?

2024-12-18 20:42 UTC, iamgirya commented on app_update/lib/src/parser/sub_parsers/version_settings_parser.dart
> -    if (unsupportedVersionsValue is! List<String>?) {
List<String>? , а не List?*

В других местах List?, я чекал

2024-12-18 20:43 UTC, iamgirya commented on app_update/lib/src/finder/update_finder.dart
>      if (sourceCheckerType != null) {
Окей, обработку перенёс на `checker.StoreChecker.getSource`

2024-12-19 20:45 UTC, StarProxima commented on app_update/test/e2e/fetcher_by_sources/fetcher_by_sources_test.dart
> +        );
Тут мб найти старое приложение, у которого есть релиз ноты на разных языках, так через vpn и разные локали можно будет проверять

2024-12-20 05:00 UTC, iamgirya commented on app_update/test/e2e/fetcher_by_sources/fetcher_by_sources_test.dart
> +        );
Можно этим заняться как починю releaseNotes

2025-01-02 15:14 UTC, StarProxima commented on app_update/test/e2e/sources_by_platform/sources_by_platform_test.dart
> +        '${Directory.current.path}\\test\\e2e\\sources_by_platform\\sources_by_platform_config.yaml',
Секс 
<img width="718" alt="image" src="https://github.com/user-attachments/assets/904baa51-e7db-4803-8795-211561708e6a" />

2025-01-02 15:14 UTC, StarProxima commented
LGTM

2025-01-02 15:14 UTC, StarProxima approved these changes

2025-01-02 15:14 UTC, merged