New cache utils
StarProxima/dev_kit pull request #7
Opened 2024-07-01 12:31 UTC by crefter

2024-07-02 00:03 UTC, StarProxima commented
Хорошо 👍

Можешь создать пр в слиптери и там затестить новое кеширование везде?

2024-07-04 17:10 UTC, StarProxima requested changes

2024-07-04 17:10 UTC, StarProxima commented on riverpod_async_builder/lib/src/riverpod_utils/lib/src/cache_utils.dart
> +  KeepAliveLink cacheFor(
@crefter Добавь плз описание, как этот метод использовать и как он работает.
Особенно важно про tag и как работает key в текущей реализации

2024-07-04 17:10 UTC, StarProxima commented on riverpod_async_builder/lib/src/riverpod_utils/lib/src/cache_utils.dart
> +    );
Мб тут тоже описать снаружи и внутри?
Чтобы было понятно, что и как и это можно было позже рефакторить и изменять при необходимости

2024-07-04 17:10 UTC, StarProxima commented on riverpod_async_builder/lib/src/riverpod_utils/lib/src/cache_utils.dart
> +  }
@crefter Подразумевалось, что кеширование с тегом работает по системе "Всё или ничего" , они диспоузяться все сразу, но даже при одном активном провайдере с тегом не диспоузится остальные (1).

Т.е. сколько бы времени не было задано, пока прослушивается один провайдер с тегом, остальные должны быть закешированы. Это нужно как раз для работы со списками. чтобы не диспоузить элементы первых страниц, которые уже были просмотрены.

При .immediately это должно работать так - есть условие (1) и условие, что указанное время ещё не прошло (2), время начинает идти сразу же после появления первого провайдера с этим тегом. Время как бы задаёт время актуальности данных.

А при .afterCancel это так - есть условие (1) и условие, что указанное время ещё не прошло (2), но время начинает идти только после того, как перестаёт выполняться условие (1), т.е. ни один провайдер больше не прослушивается. Если в это время условие (1) опять начнёт выполняться, то таймер сбрасывается и всё по новой. Время как бы задаёт то, через сколько задиспоузяться провайдеры после того, как их перестали слушать.
 
Провайдеры могут задиспоузиться, только когда оба условия (1) (2) не выполняются. Т.е, когда ни один провайдер не прослушивается, и время уже прошло. В ином случае для провайдером действует KeepAlive

2024-07-04 17:33 UTC, crefter commented on riverpod_async_builder/lib/src/riverpod_utils/lib/src/cache_utils.dart
> +  }
Понял, завтра займусь этим

2024-07-04 17:33 UTC, crefter commented on riverpod_async_builder/lib/src/riverpod_utils/lib/src/cache_utils.dart
> +    );
Хорошо, только придется переделывать все, потому после опишу

2024-07-04 17:33 UTC, crefter commented on riverpod_async_builder/lib/src/riverpod_utils/lib/src/cache_utils.dart
> +  KeepAliveLink cacheFor(
Хорошо, только придется переделывать все, потому после опишу

2024-07-05 07:42 UTC, crefter commented on riverpod_async_builder/lib/src/riverpod_utils/lib/src/cache_utils.dart
> +  }
Смотри, тогда метод _cacheFamilyForByTag не нужен, я его уберу, так как _cacheForByTag выполняет те же фугнкции, что и _cacheFamilyForByTag . Я его уберу

2024-07-05 16:43 UTC, StarProxima commented on riverpod_async_builder/lib/src/riverpod_utils/lib/src/cache_utils.dart
> +        );
Хмм, а нам не нужно при логике .afterCancel, при onResume отменять таймер, т.к. провайдеры уже прослушиваются? 🤔

Тоже самое и кешированием по тэгу

2024-07-05 17:27 UTC, crefter commented on riverpod_async_builder/lib/src/riverpod_utils/lib/src/cache_utils.dart
> +        );
В кешировании по тегу так и происходит (отменяем таймер). Хз, могу добавить

2024-07-08 21:19 UTC, StarProxima approved these changes
👍

2024-07-08 21:20 UTC, merged